import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/src/providers/query-providers";
import { AuthProvider } from "@/src/contexts/auth_context";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white text-black antialiased`}
      >
        <AuthProvider>
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
